/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivitySelectionForm: typeof import('./src/components/ActivitySelectionForm.vue')['default']
    CreateNewActivityForm: typeof import('./src/components/CreateNewActivityForm.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MyModalTemplate: typeof import('./src/components/modals/MyModalTemplate.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    ReallyCloseModal: typeof import('./src/components/modals/ReallyCloseModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveActivityDialog: typeof import('./src/components/dialogs/SaveActivityDialog.vue')['default']
    SaveModal: typeof import('./src/components/modals/SaveModal.vue')['default']
    Stopwatch: typeof import('./src/components/Stopwatch.vue')['default']
    Time: typeof import('./src/components/Time.vue')['default']
    TimeDisplay: typeof import('./src/components/TimeDisplay.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    YesNoModal: typeof import('./src/components/modals/YesNoModal.vue')['default']
  }
}
